# Generated by Django 5.0.1 on 2024-05-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addstudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registerNo', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
