# Generated by Django 5.0.1 on 2024-05-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1app', '0004_rename_name_messages_rname_messages_sname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='Rname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='Sname',
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
