# Generated by Django 5.0.1 on 2024-05-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1app', '0005_rename_rname_messages_name_remove_messages_sname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='name',
            new_name='Rname',
        ),
        migrations.AddField(
            model_name='messages',
            name='Sname',
            field=models.CharField(default='jai', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(max_length=5000),
        ),
    ]
