# Generated by Django 5.0.1 on 2024-05-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1app', '0006_rename_name_messages_rname_messages_sname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='addcontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobileNO', models.CharField(max_length=10)),
            ],
        ),
    ]
